// For CAMB Nov 2015
#define CAMB_TRANSFER_NCOL 13
#define CAMB_TRANSFER_k 0
#define CAMB_TRANSFER_Tb 2
#define CAMB_TRANSFER_Tc 1
#define CAMB_TRANSFER_Tn 5

// For class v. 2.5.0
#define CLASS_NONU_TRANSFER_NCOL 8
#define CLASS_NONU_TRANSFER_k 0
#define CLASS_NONU_TRANSFER_Tb 2
#define CLASS_NONU_TRANSFER_Tc 3
// #define CLASS_NONU_TRANSFER_Tn

#define CLASS_NU_TRANSFER_NCOL 11
#define CLASS_NU_TRANSFER_k 0
#define CLASS_NU_TRANSFER_Tb 2
#define CLASS_NU_TRANSFER_Tc 3
#define CLASS_NU_TRANSFER_Tn 5
